before_script:
  - echo "${CNPMRC}" > ~/.npmrc
  - yarn config set cache-folder /yarn.cache
  - node --version; yarn --version; ls -la

stages:
  - prepare
  - test
  - deploy

.runner: &runner
  tags:
    - node-16.13

.deploy_only_condition:
  only:
    refs:
      - master
  except:
    - schedules
    - triggers

.cache: &cache
  key:
    files:
      - yarn.lock
  paths:
    - node_modules/
    - dist/

install:
  <<: *runner
  stage: prepare
  cache:
    <<: *cache
    policy: push
  script:
    - |
      yarn install --prefer-offline
      yarn build

lint:
  <<: *runner
  stage: test
  cache:
    <<: *cache
    policy: pull
  script:
    - yarn lint

e2e:
  <<: *runner
  stage: test
  cache:
    <<: *cache
    policy: pull
  variables:
    NODE_ENV: test
  script:
    - echo 'not for now'

deploy:
  <<: *runner
  extends: .deploy_only_condition
  stage: deploy
  cache:
    <<: *cache
    policy: pull
  variables:
    NODE_ENV: production
  before_script:
    - |
      docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
      export IMAGE_TAG=${CI_COMMIT_SHA:0:7}
      export IMAGE_BASE=${CI_REGISTRY}/arkie/oauth-server
  script:
    - |
      docker/cmd
